def verificar_token (cadena)
  if cadena =~ /^([a-zA-Z]{4,5})?(\/\/)?(www.)?[\w]{2,}\.[\w]{2,}$/
    jk = 'url'
  elsif  cadena =~ /[iI][fF]/
    jk = 'pregunta'
  elsif  cadena =~ /(==|!=|<|>|<=|>=)/
    jk = 'OpRel'
  elsif  cadena =~ /[rR][eE][tT][uU][rR][nN]/
    jk = 'Retorno'
  elsif  cadena =~ /[eE][lL][sE][eE]/
    jk = 'contrario'
  elsif  cadena =~ /[tT][rR][uU][eE]/
    jk = 'Jordan'
  elsif  cadena =~ /[fF][aA][lL][sE][eE]/
    jk = 'Lebron'
  elsif  cadena =~ /[pP][rR][iI][vV][aA][tT][eE]|[pP][uU][bB][lL][iI][cC]|[pP][rR][oO][tT][eE][cC][tT][eE][dD]/
    jk = 'Alcance'
  elsif  cadena =~ /void|Void/
    jk = 'vacio'
  elsif  cadena =~ /using|Using/
    jk = 'uso'
  elsif  cadena =~ /using|Using/
    jk = 'esto'
  elsif  cadena =~ /\n/
    jk = 'cambio_linea'
=begin
  elsif  cadena =~ //
    jk = ''
  elsif  cadena =~ //
    jk = ''
  elsif  cadena =~ //
    jk = ''
  elsif  cadena =~ //
    jk = ''
=end
  elsif  cadena =~ /drawing|Drawing/
    jk = 'dibujar'
  elsif  cadena =~ /null|Null/
    jk = 'nulo'
  elsif  cadena =~ /nill|Nill/
    jk = 'valor_imaginario'
  elsif  cadena =~ /while|While/
    jk = 'mientras'
  elsif  cadena =~ /do|Do/
    jk = 'haz'
  elsif  cadena =~ /for|For|foreach|Foreach|while|While|do|Do/
    jk = 'ciclo'
  elsif  cadena =~ /int|Int|string|String|boolean|Boolean/
    jk = 'tipo_de_dato'
  elsif  cadena =~ /throw|Throw|Try|try|catch|Catch/
    jk = 'sist_control'
  elsif  cadena =~ /class|Class/
    jk = 'plantilla'
  elsif  cadena =~ /byte|Byte/
    jk = 'byte'
  elsif  cadena =~ /decimal|Decimal/
    jk = 'decimal'
  elsif  cadena =~ /Continue|continue/
    jk = 'continuar'
  elsif  cadena =~ /default|Default/
    jk = 'por_defecto'
  elsif  cadena =~ /base|Base/
    jk = 'base'
  elsif  cadena =~ /switch|Switch/
    jk = 'seleccion'
  elsif  cadena =~ /brek|Break|gotocase|GotoCase/
    jk = 'salto'
  elsif  cadena =~ /case|Case/
    jk = 'caso'
  elsif  cadena =~ /Static|static/
    jk = 'tipo_estatico'
  elsif  cadena =~ /override|Override/
    jk = 'sobrecarga'
  elsif  cadena =~ /char|Char/
    jk = 'Caracter'
  elsif  cadena =~ /event|Event/
    jk = 'Evento'
  elsif  cadena =~ /New|new/
    jk = 'nuevo'
  elsif  cadena =~ /goto|Goto/
    jk = 'ir_a'
  elsif  cadena =~ /object|Object/
    jk = 'objeto'
  elsif  cadena =~ /system|System/
    jk = 'sistema'
  elsif  cadena =~ /lenght|Lenght/
    jk = 'largo'
  elsif  cadena =~ /Math|math/
    jk = 'matematica'
  elsif  cadena =~ /random|Random/
    jk = 'Aleatorio'
  elsif  cadena =~ /struct|Struct/
    jk = 'estructura'
  elsif  cadena =~ /delegate|Delegate/
    jk = 'delegado'
  elsif  cadena =~ /namespace|Namespace/
    jk = 'Relleno'
  elsif  cadena =~ /select|Select/
    jk = 'seleccion'
  elsif  cadena =~ /order|Order/
    jk = 'ordenar'
  elsif  cadena =~ /ascending|Ascending/
    jk = 'ascendente'
  elsif  cadena =~ /descending|Descending/
    jk = 'descendente'
  elsif  cadena =~ /where|Where/
    jk = 'donde'
  elsif  cadena =~ /add|Add/
    jk = 'agregar'
  elsif  cadena =~ /remove|Remove/
    jk = 'remover'
  elsif  cadena =~ /get|Get/
    jk = 'obtener'
  elsif  cadena =~ /Set|set/
    jk = 'asignar'
  elsif  cadena =~ /from|From/
    jk = 'de (origen)'
  elsif  cadena =~ /abs|Abs/
    jk = 'absoluto'
  elsif  cadena =~ /exp|Exp/
    jk = 'exponencial'
  elsif  cadena =~ /max|Max/
    jk = 'maximo'
  elsif  cadena =~ /min|Min/
    jk = 'minimo'
  elsif  cadena =~ /pow|Pow/
    jk = 'potencia'
  elsif  cadena =~ /sqrt|Sqrt/
    jk = 'Raiz Cuadrada'
  elsif  cadena =~ /round|Round/
    jk = 'Redondear'
  elsif  cadena =~ /clear|Clear/
    jk = 'limpiar'
  elsif  cadena =~ /color|Color/
    jk = 'Color'
  elsif  cadena =~ /point|Point/
    jk = 'Punto'
  elsif  cadena =~ /pen|Pen/
    jk = 'pluma'
  elsif  cadena =~ /And|and/
    jk = '(y)'
  elsif  cadena =~ /not|Not/
    jk = 'no'
  elsif  cadena =~ /print|Print/
    jk = 'Imprimir'
  elsif  cadena =~ /^import|Import$/
    jk = 'importar'
  elsif  cadena =~ /raise|Raise/
    jk = 'alzar'
  elsif  cadena =~ /pass|Pass/
    jk = 'pasar'
  elsif  cadena =~ /except|Except/
    jk = 'excepto'
  elsif  cadena =~ /def|Def/
    jk = 'definicion'
  elsif  cadena =~ /replace|Replace/
    jk = 'reemplazar'
  elsif  cadena =~ /exec|Exec/
    jk = 'ejecutar'
  elsif  cadena =~ /finally|Finally/
    jk = 'finalmente'
  elsif  cadena =~ /del|Del/
    jk = 'borrar'
  elsif  cadena =~ /filter|Filter/
    jk = 'filtrar'
  elsif  cadena =~ /lambda|Lambda/
    jk = 'funcion anonima'
  elsif  cadena =~ /elif|Elif/
    jk = 'sino'
  elsif  cadena =~ /global|Global/
    jk = 'globar'
  elsif  cadena =~ /assert|Assert/
    jk = 'revisar'
  elsif  cadena =~ /yield|Yield/
    jk = 'Generar'
  elsif  cadena =~ /extent|Extent/
    jk = 'extender'
  elsif  cadena =~ /rand|Rand/
    jk = 'aleatorio'
  elsif  cadena =~ /continue|Continue/
    jk = 'continuar'
  elsif  cadena =~ /instanceof|Instanceof/
    jk = 'Instancia'
  elsif  cadena =~ /package|Package/
    jk = 'importar paquete'
  elsif  cadena =~ /enum|Enum/
    jk = 'enumera'
  elsif  cadena =~ /native|Native/
    jk = 'nativo'
  elsif  cadena =~ /interface|Interface/
    jk = 'interfaz'
  elsif  cadena =~ /quit|Quit/
    jk = 'terminar'
  elsif  cadena =~ /exit|Exit/
    jk = 'salir'
  elsif  cadena =~ /type|Type/
    jk = 'tipo'
  elsif  cadena =~ /body|Body/
    jk = 'cuerpo'
  elsif  cadena =~ /link|Link/
    jk = 'enlace'
  elsif  cadena =~ /head|Head/
    jk = 'encabezado'
  elsif  cadena =~ /archive|Archive/
    jk = 'archivo'
  elsif  cadena =~ /form|Form/
    jk = 'formulario'
  elsif  cadena =~ /button|Button/
    jk = 'boton'
  elsif  cadena =~ /checkbox|Checkbox/
    jk = 'chequeo'
  elsif  cadena =~ /script|Script/
    jk = 'escrito'
  elsif  cadena =~ /app|App/
    jk = 'aplicacion'
  elsif  cadena =~ /controller|Controller/
    jk = 'controlador'
  elsif  cadena =~ /expect|Expect/
    jk = 'comprobar'
  elsif  cadena =~ /\$watch/
    jk = 'observar'
  elsif  cadena =~ /\$apply/
    jk = 'aplicar'
  elsif  cadena =~ /\.affix/
    jk = 'bloqueado'
  elsif  cadena =~ /position:fixed/
    jk = 'posicion fija'
  elsif  cadena =~ /\.alert/
    jk = 'alerta'
  elsif  cadena =~ /\.alert-success/
    jk = 'alerta - exito'
  elsif  cadena =~ /\.close/
    jk = 'estilo - alerta'
  elsif  cadena =~ /\.active/
    jk = 'activo'
  elsif  cadena =~ /\.disabled/
    jk = 'desactivado'
  elsif  cadena =~ /\(/
    jk = 'parI'
  elsif  cadena =~ /\)/
    jk = 'parD'
  elsif  cadena =~ /\.slide/
    jk = 'deslizar'
  elsif  cadena =~ /\.item/
    jk = 'item'
  elsif  cadena =~ /\.collapse/
    jk = 'colapsar'
  elsif  cadena =~ /\.collapsing/
    jk = 'colapsando'
  elsif  cadena =~ /shuffle|Shuffle/
    jk = 'desordernar'
  elsif  cadena =~ /extract|Extract/
    jk = 'extraer'
  elsif  cadena =~ /compact/
    jk = 'arreglo-compacto'#CUENTA DE PALABRAS 120
  elsif  cadena =~ /contains|Contains/
    jk = 'contiene'
  elsif  cadena =~ /submit|Submit/
    jk = 'enviar'
  elsif  cadena =~ /stop|Stop/
    jk = 'parar'
  elsif  cadena =~ /load|Load/
    jk = 'cargar'
  elsif  cadena =~ /clipevent|Clipevent/
    jk = 'evento-objecto'
  elsif  cadena =~ /batch|Batch/
    jk = 'lote'
  elsif  cadena =~ /trace|Trace/
    jk = 'rastro'
  elsif  cadena =~ /press|Press/
    jk = 'presionar'
  elsif  cadena =~ /release|Release/
    jk = 'liberar'
  elsif  cadena =~ /^car$/
    jk = 'primero'#CUENTA DE PALABRAS 130
  elsif  cadena =~ /cons/
    jk = 'principio'
  elsif  cadena =~ /eq/
    jk = 'igualdad'
  elsif  cadena =~ /equal/
    jk = 'comparador - listas'
  elsif  cadena =~ /quote/
    jk = 'ignorar-valor'
  elsif  cadena =~ /mod/
    jk = 'modulo'
  elsif  cadena =~ /jmp/
    jk = 'salto'
  elsif  cadena =~ /cal/
    jk = 'llamada'
  elsif  cadena =~ /include|Include/
    jk = 'incluir'
  elsif  cadena =~ /mov/
    jk = 'mover'
  elsif  cadena =~ /DumpRegs/
    jk = 'registros'#CUENTA DE PALABRAS 140
  elsif  cadena =~ /ExitProcess/
    jk = 'fin-proceso'
  elsif  cadena =~ /flock/
    jk = 'fijo (archivo)'
  elsif  cadena =~ /fork/
    jk = 'extender (carga)'
  elsif  cadena =~ /pop/
    jk = 'ultimo'
  elsif  cadena =~ /study/
    jk = 'estudiar'   #MARCADOR ACTUAL
  elsif  cadena =~ /sub/
    jk = 'subrutina'
  elsif  cadena =~ /die/
    jk = 'excepcion'
  elsif  cadena =~ /utime/
    jk = 'tiempo'
  elsif  cadena =~ /truncate/
    jk = 'truncar'
  elsif  cadena =~ /prototype/
    jk = 'prototipo'#CUENTA DE PALABRAS 150
  elsif  cadena =~ /quotemeta/
    jk = 'metaletra'
  elsif  cadena =~ /redo/
    jk = 'rehacer'
  elsif  cadena =~ /warn/
    jk = 'advertencia'
  elsif  cadena =~ /\}/
    jk = 'llaveDer'
  elsif  cadena =~ /\{/
    jk = 'llaveIzq'
  elsif  cadena =~ /^[\w]{2,}@[a-z]+\.[\w]{2,}\\.[\w]{2,}?$/
    jk = 'correo'
  elsif  cadena =~ /^(\\+|-)?+\\d+((\\.)\\d+|e(\\+|-)?\\d+|\\.+e(\\+|-)?\\d+)?$/
    jk = 'numero'
  elsif  cadena =~ /^[a-zA-Z]+([0-9]*[a-z]*)?$/
    jk = 'id'
  elsif cadena =~ /\\n/
    jk = 'linea'
  else
    jk = 'desconocido'
  end
  return jk
  puts cadena
end


def test (v1)
  puts v1
end
